# Generated by Django 4.0.4 on 2022-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=50)),
                ('Player', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('On_start', models.IntegerField()),
                ('Points_Average', models.IntegerField()),
                ('Last_5_games_points', models.IntegerField()),
                ('J_4', models.IntegerField()),
                ('J_3', models.IntegerField()),
                ('J_2', models.IntegerField()),
                ('J_1', models.IntegerField()),
                ('J_Actual', models.IntegerField()),
                ('Avg_last_5_games', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Squad_Average_Points', models.IntegerField()),
                ('J_4_Squad_Points', models.IntegerField()),
                ('J_3_Squad_Points', models.IntegerField()),
                ('J_2_Squad_Points', models.IntegerField()),
                ('J_1_Squad_Points', models.IntegerField()),
                ('J_Actual_Squad_Points', models.IntegerField()),
                ('Squad_Avg_last_5_Games', models.IntegerField()),
                ('Value_Squad', models.IntegerField()),
                ('vs', models.CharField(max_length=50)),
                ('Vs_Team', models.CharField(max_length=50)),
                ('Vs_Squad_Average_Points', models.IntegerField()),
                ('J_4_Vs_Squad_Points', models.IntegerField()),
                ('J_3_Vs_Squad_Points', models.IntegerField()),
                ('J_2_Vs_Squad_Points', models.IntegerField()),
                ('J_1_Vs_Squad_Points', models.IntegerField()),
                ('J_Actual_Vs_Squad_Points', models.IntegerField()),
                ('Vs_Squad_Avg_last_5_Games', models.IntegerField()),
                ('Vs_Value_Squad', models.IntegerField()),
                ('Team_clas', models.IntegerField()),
                ('Vs_Team_clas', models.IntegerField()),
            ],
        ),
    ]
