# Generated by Django 4.0.4 on 2022-05-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_allplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
        migrations.DeleteModel(
            name='AllPlayers',
        ),
    ]
